unit TestFuncoes;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, System.DateUtils, Vcl.Dialogs, Funcoes, System.SysUtils;

type
  // Test methods for class TFuncao

  TestTFuncao = class(TTestCase)
  strict private
    FFuncao: TFuncao;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestCampoVazio;
    procedure TestCampoValorValido;
    procedure TestFormataValor;
    procedure TestValidaData;
    procedure TestCalculaValorComImposto;
  end;

implementation

procedure TestTFuncao.SetUp;
begin
  FFuncao := TFuncao.Create;
end;

procedure TestTFuncao.TearDown;
begin
  FFuncao.Free;
  FFuncao := nil;
end;

procedure TestTFuncao.TestCampoVazio;
var
  ReturnValue: Boolean;
  pEnviaMensagem: Boolean;
  pCampo: string;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFuncao.CampoVazio(pCampo, pEnviaMensagem);
  // TODO: Validate method results
end;

procedure TestTFuncao.TestCampoValorValido;
var
  ReturnValue: Boolean;
  pEnviaMensagem: Boolean;
  pCampo: string;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFuncao.CampoValorValido(pCampo, pEnviaMensagem);
  // TODO: Validate method results
end;

procedure TestTFuncao.TestFormataValor;
var
  ReturnValue: string;
  pEnviaMensagem: Boolean;
  pCampo: string;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFuncao.FormataValor(pCampo, pEnviaMensagem);
  // TODO: Validate method results
end;

procedure TestTFuncao.TestValidaData;
var
  ReturnValue: Boolean;
  pEnviaMensagem: Boolean;
  pData: string;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFuncao.ValidaData(pData, pEnviaMensagem);
  // TODO: Validate method results
end;

procedure TestTFuncao.TestCalculaValorComImposto;
var
  ReturnValue: Double;
  pValor: Double;
begin
  // TODO: Setup method call parameters
  ReturnValue := FFuncao.CalculaValorComImposto(pValor);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFuncao.Suite);
end.

